{
 "title": "Generation and Demand",
 "time": { "from": "2023-01-01T00:00:00.000Z", "to": "2023-01-31T23:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "country",
    "query": "SHOW TAG VALUES WITH KEY = \"country\" "
   },
   {
    "name": "state",
    "query": "SHOW TAG VALUES WITH KEY = \"state\" WHERE value != 'Common'"
   },
   {
    "name": "mode",
    "query": "SHOW TAG VALUES WITH KEY = \"mode\""
   },
   {
    "name": "balanced",
    "query": "SHOW TAG VALUES WITH KEY = \"balanced\""
   }
  ]
 },
 "panels": [
  {
   "title": "Generation per type per country",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Generation per type in $country",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "alias": "Hydro $tag_country",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "per_type_gen",
     "query": "SELECT sum(\"Generation [MW]\")/4\nFROM \"per_type_gen\"\nWHERE ((\"technology\" = 'Hydro Run-of-river and poundage' OR \"technology\" = 'Hydro Water Reservoir') AND \"country\" =~ /^$country$/) AND $timeFilter \nGROUP BY time(1h), \"country\" fill(null) \nORDER BY time DESC",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Hydro" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    },
    {
     "alias": "Biomass $tag_country",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "per_type_gen",
     "query": "SELECT mean(\"Generation [MW]\") FROM \"Per_type_gen\" WHERE (\"technology\" = 'Biomass' AND \"country\" =~ /^$country$/) AND $timeFilter GROUP BY time(1h), \"country\" fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Biomass" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    },
    {
     "alias": "Nuclear $tag_country",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "per_type_gen",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Nuclear" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    },
    {
     "alias": "Lignite $tag_country",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "per_type_gen",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Fossil Brown coal/Lignite" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    },
    {
     "alias": "Hard coal $tag_country",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "per_type_gen",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Fossil Hard coal" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    },
    {
     "alias": "Gas $tag_country",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "per_type_gen",
     "query": "SELECT sum(\"Generation [MW]\") FROM \"Per_type_gen\" WHERE ((\"technology\" = 'Fossil Gas' OR \"technology\" = 'Fossil Coal-derived gas') AND \"country\" =~ /^$state$/) AND $timeFilter GROUP BY time(1h), \"country\" fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Fossil Gas" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    },
    {
     "alias": "Oil $tag_country",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "per_type_gen",
     "query": "SELECT mean(\"Generation [MW]\") FROM \"Per_type_gen\" WHERE (\"technology\" = 'Oil' AND \"country\" =~ /^$country$/) AND $timeFilter GROUP BY time(1h), \"country\" fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Fossil Oil" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    },
    {
     "alias": "Other fossil $tag_country",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "per_type_gen",
     "query": "SELECT sum(\"Generation [MW]\")/4\nFROM \"per_type_gen\" WHERE ((\"technology\" = 'Fossil Coal-derived gas' OR \"technology\" = 'Fossil Oil shale' OR \"technology\" = 'Waste' OR \"technology\" = 'Other' OR \"technology\" = 'Fossil Peat') AND \"country\" =~ /^$country$/) AND $timeFilter \nGROUP BY time(1h), \"country\" fill(null) \nORDER BY time DESC",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Fossil Coal-derived gas" },
      { "condition": "OR", "key": "technology", "operator": "=", "value": "Fossil Oil shale" },
      { "condition": "OR", "key": "technology", "operator": "=", "value": "Waste" },
      { "condition": "OR", "key": "technology", "operator": "=", "value": "Other" },
      { "condition": "OR", "key": "technology", "operator": "=", "value": "Fossil Peat" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    },
    {
     "alias": "Wind Onshore $tag_country",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "per_type_gen",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Wind Onshore" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    },
    {
     "alias": "Wind Offshore $tag_country",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "per_type_gen",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Wind Offshore" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    },
    {
     "alias": "Solar $tag_country",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "per_type_gen",
     "query": "SELECT sum(\"Total capacity\")  / 4 FROM \"Capacities\" WHERE (\"simulationID\" =~ /^$Scenario$/ AND \"technology\" = 'Renewable' AND \"UnitName\" = 'Solar [MW]') AND $timeFilter GROUP BY time(1h), \"technology\", \"UnitName\" fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Solar" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    },
    {
     "alias": "Other VRE $tag_country",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "per_type_gen",
     "query": "SELECT sum(\"Generation [MW]\")/4 \nFROM \"per_type_gen\" \nWHERE ((\"technology\" = 'Other renewable' OR \"technology\" = 'Geothermal' OR \"technology\" = 'Marine') AND \"country\" =~ /^$country$/) AND $timeFilter \nGROUP BY time(1h), \"country\" fill(null) \nORDER BY time DESC",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Other renewable" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    },
    {
     "alias": "Storage discharge $tag_country",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "per_type_gen",
     "query": "SELECT sum(\"Generation [MW]\")/4\nFROM \"per_type_gen\"\nWHERE (\"technology\" = 'Hydro Pumped Storage' AND \"country\" =~ /^$country$/) AND $timeFilter AND \"Generation [MW]\" >= 0\nGROUP BY time(1h), \"country\" fill(null)\nORDER BY time DESC",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Hydro" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    },
    {
     "alias": "Storage charge $tag_country",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "per_type_gen",
     "query": "SELECT sum(\"Generation [MW]\")/4\nFROM \"per_type_gen\"\nWHERE (\"technology\" = 'Hydro Pumped Storage' AND \"country\" =~ /^$country$/) AND $timeFilter AND \"Generation [MW]\" < 0\nGROUP BY time(1h), \"country\" fill(null)\nORDER BY time DESC",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Hydro" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Demand per country",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Demand in $country",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "alias": "Actual demand $tag_country",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "country" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "demand",
       "select": [
        [
         { "params": [ "Demand [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "country", "operator": "=~", "value": "/^$country$/" }
       ]
      },
      {
       "alias": "Forecasted demand $tag_country",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "country" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "demand_forecast",
       "select": [
        [
         { "params": [ "Demand [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "country", "operator": "=~", "value": "/^$country$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cross-border flows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cross-border flows in/out $country",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "alias": "Flow from $tag_from",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "from" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cross_border_flow",
       "select": [
        [
         { "params": [ "Flow [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 4" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "from", "operator": "=~", "value": "/^$country$/" }
       ]
      },
      {
       "alias": "Flow into $tag_to",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "to" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cross_border_flow",
       "select": [
        [
         { "params": [ "Flow [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 4" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "to", "operator": "=~", "value": "/^$country$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Regionalized data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total reg. generation",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "alias": "Hydro",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "query": "SELECT sum(\"Generation [MW]\") FROM \"Reg_generation\" WHERE ((\"technology\" = 'Other renewable' OR \"technology\" = 'Geothermal' OR \"technology\" = 'Marine') AND \"state\" =~ /^$state$/ AND \"mode\"='api_version') AND $timeFilter GROUP BY time(1h), \"state\" fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        {
         "condition": "AND",
         "key": "technology",
         "operator": "=",
         "value": "Hydro Run-of-river and poundage"
        },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Biomass",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "query": "SELECT sum(\"Generation [MW]\") FROM \"Per_type_gen\" WHERE (\"technology\" = 'Biomass' AND \"country\" =~ /^$state$/) AND $timeFilter GROUP BY time(1h), \"country\" fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Biomass" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Nuclear",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Nuclear" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Lignite",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Fossil Brown coal/Lignite" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Hard coal",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Fossil Hard coal" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Fossil gas",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "query": "SELECT sum(\"Generation [MW]\") FROM \"Per_type_gen\" WHERE ((\"technology\" = 'Fossil Gas' OR \"technology\" = 'Fossil Coal-derived gas') AND \"country\" =~ /^$state$/) AND $timeFilter GROUP BY time(1h), \"country\" fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Fossil Gas" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Oil",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "query": "SELECT sum(\"Generation [MW]\") FROM \"Per_type_gen\" WHERE ((\"technology\" = 'Fossil Gas' OR \"technology\" = 'Fossil Coal-derived gas') AND \"country\" =~ /^$state$/) AND $timeFilter GROUP BY time(1h), \"country\" fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Fossil Oil" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Other fossil",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "query": "SELECT sum(\"Generation [MW]\") FROM \"reg_generation\" WHERE ((\"technology\" = 'Other' OR \"technology\" = 'Waste' OR \"technology\" = 'Fossil Coal-derived gas') AND \"mode\" =~ /^$mode$/ AND \"balanced\" =~ /^$balanced$/) AND $timeFilter GROUP BY time(1h) fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Other" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" },
        { "condition": "OR", "key": "technology", "operator": "=", "value": "Waste" }
       ]
      },
      {
       "alias": "Wind Onshore",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Wind Onshore" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Wind Offshore",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Wind Offshore" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Solar",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "query": "SELECT sum(\"Total capacity\")  / 4 FROM \"Capacities\" WHERE (\"simulationID\" =~ /^$Scenario$/ AND \"technology\" = 'Renewable' AND \"UnitName\" = 'Solar [MW]') AND $timeFilter GROUP BY time(1h), \"technology\", \"UnitName\" fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Solar" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Other VRE",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "query": "SELECT sum(\"Generation [MW]\") FROM \"Reg_generation\" WHERE ((\"technology\" = 'Other renewable' OR \"technology\" = 'Geothermal' OR \"technology\" = 'Marine') AND \"state\" =~ /^$state$/ AND \"mode\"='api_version') AND $timeFilter GROUP BY time(1h), \"state\" fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Geothermal" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Storage charge",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "query": "SELECT sum(\"Generation [MW]\") FROM \"reg_generation\" WHERE (\"technology\" = 'Hydro Pumped Storage' AND \"mode\" =~ /^$mode$/ AND \"balanced\" =~ /^$balanced$/ AND \"Generation [MW]\" < 0) AND $timeFilter GROUP BY time(1h) fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Hydro Pumped Storage" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Storage discharge",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "country" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "query": "SELECT sum(\"Generation [MW]\") FROM \"reg_generation\" WHERE (\"technology\" = 'Hydro Pumped Storage' AND \"mode\" =~ /^$mode$/ AND \"balanced\" =~ /^$balanced$/ AND \"Generation [MW]\" >= 0) AND $timeFilter GROUP BY time(1h) fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Hydro" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
        { "condition": "AND", "key": "mode", "operator": "=", "value": "api_version" }
       ]
      }
     ]
    },
    {
     "title": "Generation per state",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "alias": "Hydro $tag_state",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "query": "SELECT sum(\"Generation [MW]\") FROM \"Reg_generation\" WHERE ((\"technology\" = 'Other renewable' OR \"technology\" = 'Geothermal' OR \"technology\" = 'Marine') AND \"state\" =~ /^$state$/ AND \"mode\"='api_version') AND $timeFilter GROUP BY time(1h), \"state\" fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        {
         "condition": "AND",
         "key": "technology",
         "operator": "=",
         "value": "Hydro Run-of-river and poundage"
        },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Biomass $tag_state",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "query": "SELECT sum(\"Generation [MW]\") FROM \"Per_type_gen\" WHERE (\"technology\" = 'Biomass' AND \"country\" =~ /^$state$/) AND $timeFilter GROUP BY time(1h), \"country\" fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Biomass" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Nuclear $tag_state",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Nuclear" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Lignite $tag_state",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Fossil Brown coal/Lignite" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Hard coal $tag_state",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Fossil Hard coal" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Fossil gas $tag_state",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "query": "SELECT sum(\"Generation [MW]\") FROM \"Per_type_gen\" WHERE ((\"technology\" = 'Fossil Gas' OR \"technology\" = 'Fossil Coal-derived gas') AND \"country\" =~ /^$state$/) AND $timeFilter GROUP BY time(1h), \"country\" fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Fossil Gas" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Oil $tag_state",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "query": "SELECT sum(\"Generation [MW]\") FROM \"Per_type_gen\" WHERE ((\"technology\" = 'Fossil Gas' OR \"technology\" = 'Fossil Coal-derived gas') AND \"country\" =~ /^$state$/) AND $timeFilter GROUP BY time(1h), \"country\" fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Fossil Oil" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Other fossil $tag_state",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "query": "SELECT sum(\"Generation [MW]\") FROM \"reg_generation\" WHERE ((\"technology\" = 'Other' OR \"technology\" = 'Waste' OR \"technology\" = 'Fossil Coal-derived gas') AND \"state\" =~ /^$state$/ AND \"mode\" =~ /^$mode$/ AND \"balanced\" =~ /^$balanced$/) AND $timeFilter GROUP BY time(1h), \"state\" fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Other" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" },
        { "condition": "OR", "key": "technology", "operator": "=", "value": "Waste" }
       ]
      },
      {
       "alias": "Wind Onshore $tag_state",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Wind Onshore" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Wind Offshore $tag_state",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Wind Offshore" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Solar $tag_state",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "query": "SELECT sum(\"Total capacity\")  / 4 FROM \"Capacities\" WHERE (\"simulationID\" =~ /^$Scenario$/ AND \"technology\" = 'Renewable' AND \"UnitName\" = 'Solar [MW]') AND $timeFilter GROUP BY time(1h), \"technology\", \"UnitName\" fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Solar" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Other VRE $tag_state",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "query": "SELECT sum(\"Generation [MW]\") FROM \"Reg_generation\" WHERE ((\"technology\" = 'Other renewable' OR \"technology\" = 'Geothermal' OR \"technology\" = 'Marine') AND \"state\" =~ /^$state$/ AND \"mode\"='api_version') AND $timeFilter GROUP BY time(1h), \"state\" fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Geothermal" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Storage charge $tag_state",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "query": "SELECT sum(\"Generation [MW]\") FROM \"reg_generation\" WHERE (\"technology\" = 'Hydro Pumped Storage' AND \"state\" =~ /^$state$/ AND \"mode\" =~ /^$mode$/ AND \"balanced\" =~ /^$balanced$/ AND \"Generation [MW]\" < 0) AND $timeFilter GROUP BY time(1h), \"state\" fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Hydro Pumped Storage" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
        { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
        { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
       ]
      },
      {
       "alias": "Storage discharge $tag_state",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "country" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_generation",
       "query": "SELECT sum(\"Generation [MW]\") FROM \"reg_generation\" WHERE (\"technology\" = 'Hydro Pumped Storage' AND \"state\" =~ /^$state$/ AND \"mode\" =~ /^$mode$/ AND \"balanced\" =~ /^$balanced$/ AND \"Generation [MW]\" >= 0) AND $timeFilter GROUP BY time(1h), \"state\" fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Hydro" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
        { "condition": "AND", "key": "mode", "operator": "=", "value": "api_version" }
       ]
      }
     ]
    },
    {
     "title": "Demand per state",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "alias": "Demand $tag_state",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "reg_demand",
       "select": [
        [
         { "params": [ "Demand [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Generation per unit in DE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Generation per unit",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "alias": "Nuclear",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "per_unit_gen",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Nuclear" }
       ]
      },
      {
       "alias": "Lignite",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "per_unit_gen",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Fossil Brown coal/Lignite" }
       ]
      },
      {
       "alias": "Hard coal",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "country" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "per_unit_gen",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Fossil Hard coal" }
       ]
      },
      {
       "alias": "Gas",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "country" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "per_unit_gen",
       "query": "SELECT sum(\"Generation [MW]\") FROM \"Per_type_gen\" WHERE ((\"technology\" = 'Fossil Gas' OR \"technology\" = 'Fossil Coal-derived gas') AND \"country\" =~ /^$state$/) AND $timeFilter GROUP BY time(1h), \"country\" fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Fossil Gas" }
       ]
      },
      {
       "alias": "Oil",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "country" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "per_unit_gen",
       "query": "SELECT sum(\"Generation [MW]\") FROM \"Per_type_gen\" WHERE ((\"technology\" = 'Fossil Gas' OR \"technology\" = 'Fossil Coal-derived gas') AND \"country\" =~ /^$state$/) AND $timeFilter GROUP BY time(1h), \"country\" fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Fossil Oil" }
       ]
      },
      {
       "alias": "Other fossil",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "per_unit_gen",
       "query": "SELECT sum(\"Generation [MW]\") FROM \"Per_type_gen\" WHERE ((\"technology\" = 'Other' OR \"technology\" = 'Waste' AND \"technology\" = 'Fossil Oil shale' AND \"technology\" = 'Fossil Peat' AND \"technology\" = 'Fossil Coal-derived gas') AND \"country\" =~ /^$state$/) AND $timeFilter GROUP BY time(1h), \"country\" fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "technology", "operator": "=", "value": "Waste" },
        { "condition": "OR", "key": "technology", "operator": "=", "value": "Fossil Coal-derived gas" }
       ]
      },
      {
       "alias": "Hydro",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "per_unit_gen",
       "query": "SELECT mean(\"Generation [MW]\") FROM \"Per_type_gen\" WHERE ((\"technology\" = 'Hydro Pumped Storage' OR \"technology\" = 'Hydro Run-of-river and poundage' OR \"technology\" = 'Hydro Water Reservoir') AND \"country\" =~ /^$state$/) AND $timeFilter GROUP BY time(15m), \"country\" fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        {
         "condition": "AND",
         "key": "technology",
         "operator": "=",
         "value": "Hydro Run-of-river and poundage"
        },
        { "condition": "OR", "key": "technology", "operator": "=", "value": "Hydro Water Reservoir" }
       ]
      },
      {
       "alias": "Storage",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "per_unit_gen",
       "query": "SELECT mean(\"Generation [MW]\") FROM \"Per_type_gen\" WHERE ((\"technology\" = 'Hydro Pumped Storage' OR \"technology\" = 'Hydro Run-of-river and poundage' OR \"technology\" = 'Hydro Water Reservoir') AND \"country\" =~ /^$state$/) AND $timeFilter GROUP BY time(15m), \"country\" fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "OR", "key": "technology", "operator": "=", "value": "Hydro Pumped Storage" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "VRE from ERA5",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "VRE historical",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "alias": "Total Solar DE (ERA5)",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vre_gen",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "technology", "operator": "=", "value": "Solar" }
       ]
      },
      {
       "alias": "Total Solar $tag_country (ENTSO-E) ",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "country" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "per_type_gen",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "technology", "operator": "=", "value": "Solar" },
        { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" }
       ]
      },
      {
       "alias": "Total Wind Onshore DE (ERA5)",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vre_gen",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "technology", "operator": "=", "value": "Onshore" }
       ]
      },
      {
       "alias": "Total Wind Onshore  $tag_country (ENTSO-E)",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "country" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "per_type_gen",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "technology", "operator": "=", "value": "Wind Onshore" },
        { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" }
       ]
      }
     ]
    },
    {
     "title": "VRE forecast",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "alias": "Solar $tag_state",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vre_forecast",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "technology", "operator": "=", "value": "Solar" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
        { "condition": "AND", "key": "state", "operator": "!=", "value": "DE" }
       ]
      },
      {
       "alias": "Total Solar (meteo)",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vre_forecast",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "technology", "operator": "=", "value": "Solar" },
        { "condition": "AND", "key": "state", "operator": "!=", "value": "DE" }
       ]
      },
      {
       "alias": "Total Solar (ENTSO-E)",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vre_forecast",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "technology", "operator": "=", "value": "Solar" },
        { "condition": "AND", "key": "state", "operator": "=", "value": "DE" }
       ]
      },
      {
       "alias": "Wind Onshore $tag_state",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vre_forecast",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "technology", "operator": "=", "value": "Onshore" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
        { "condition": "AND", "key": "state", "operator": "!=", "value": "DE" }
       ]
      },
      {
       "alias": "Total Wind Onshore (meteo)",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vre_forecast",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "technology", "operator": "=", "value": "Onshore" },
        { "condition": "AND", "key": "state", "operator": "!=", "value": "DE" }
       ]
      },
      {
       "alias": "Total Wind Onshore (ENTSO-E)",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vre_forecast",
       "select": [
        [
         { "params": [ "Generation [MW]" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "technology", "operator": "=", "value": "Onshore" },
        { "condition": "AND", "key": "state", "operator": "=", "value": "DE" }
       ]
      }
     ]
    }
   ]
  }
 ]
}