{
 "title": "Emission intensities and regionalized data (TimescaleDB)",
 "time": { "from": "2022-12-31T23:00:00.000Z", "to": "2023-12-31T22:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "state",
    "query": "SELECT DISTINCT state FROM cosema.reg_generation WHERE state NOT IN ('Common', 'NW') ORDER BY 1"
   },
   {
    "name": "mode",
    "query": "SELECT DISTINCT mode FROM cosema.reg_generation ORDER BY 1"
   },
   {
    "name": "balanced",
    "query": "SELECT DISTINCT balanced FROM cosema.reg_generation ORDER BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Emissions intensity in $state",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('1 hour', \"time\") AS \"time\",\n  AVG(\"Intensity [g/kWh]\") FILTER (WHERE type='consumption' AND state='$state') AS \"Consumption intensity $state\",\n  AVG(\"Intensity [g/kWh]\") FILTER (WHERE type='production' AND state='$state') AS \"Generation intensity $state\",\n  AVG(\"Intensity [g/kWh]\") FILTER (WHERE type='consumption' AND state='DE') AS \"Consumption intensity DE\",\n  AVG(\"Intensity [g/kWh]\") FILTER (WHERE type='production' AND state='DE') AS \"Generation intensity DE\"\nFROM cosema.co2_intensity\nWHERE mode='$mode' AND $__timeFilter(\"time\")\nGROUP BY 1 ORDER BY 1"
    }
   ]
  },
  {
   "title": "Emissions intensity forecast",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('1 hour', \"time\") AS \"time\",\n  AVG(\"Intensity [g/kWh]\") FILTER (WHERE type='Consumption' AND state='$state') AS \"Forecasted consumption intensity $state\",\n  AVG(\"Intensity [g/kWh]\") FILTER (WHERE type='Generation' AND state='$state') AS \"Forecasted generation intensity $state\",\n  AVG(\"Intensity [g/kWh]\") FILTER (WHERE type='Consumption' AND state='DE') AS \"Forecasted consumption intensity DE\",\n  AVG(\"Intensity [g/kWh]\") FILTER (WHERE type='Generation' AND state='DE') AS \"Forecasted generation intensity DE\"\nFROM cosema.co2_intensity\nWHERE mode='forecast' AND $__timeFilter(\"time\")\nGROUP BY 1 ORDER BY 1"
    }
   ]
  },
  {
   "title": "Generation in $state",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('1 hour', \"time\") AS \"time\",\n  SUM(\"Generation [MW]\") FILTER (WHERE technology IN ('Hydro Run-of-river and poundage','Hydro Water Reservoir')) AS \"Hydro\",\n  SUM(\"Generation [MW]\") FILTER (WHERE technology = 'Biomass') AS \"Biomass\",\n  SUM(\"Generation [MW]\") FILTER (WHERE technology = 'Nuclear') AS \"Nuclear\",\n  SUM(\"Generation [MW]\") FILTER (WHERE technology = 'Fossil Brown coal/Lignite') AS \"Lignite\",\n  SUM(\"Generation [MW]\") FILTER (WHERE technology = 'Fossil Hard coal') AS \"Hard coal\",\n  SUM(\"Generation [MW]\") FILTER (WHERE technology = 'Fossil Gas') AS \"Fossil gas\",\n  SUM(\"Generation [MW]\") FILTER (WHERE technology = 'Fossil Oil') AS \"Oil\",\n  SUM(\"Generation [MW]\") FILTER (WHERE technology IN ('Fossil Coal-derived gas','Fossil Oil shale','Waste','Other','Fossil Peat')) AS \"Other fossil\",\n  SUM(\"Generation [MW]\") FILTER (WHERE technology = 'Wind Onshore') AS \"Wind Onshore\",\n  SUM(\"Generation [MW]\") FILTER (WHERE technology = 'Wind Offshore') AS \"Wind Offshore\",\n  SUM(\"Generation [MW]\") FILTER (WHERE technology = 'Solar') AS \"Solar\",\n  SUM(\"Generation [MW]\") FILTER (WHERE technology IN ('Other renewable','Geothermal','Marine')) AS \"Other VRE\",\n  SUM(\"Generation [MW]\") FILTER (WHERE technology = 'Hydro Pumped Storage' AND \"Generation [MW]\" <= 0) AS \"Storage charge\",\n  SUM(\"Generation [MW]\") FILTER (WHERE technology = 'Hydro Pumped Storage' AND \"Generation [MW]\" > 0) AS \"Storage discharge\"\nFROM cosema.reg_generation\nWHERE state = '$state' AND mode = '$mode' AND balanced = '$balanced' AND $__timeFilter(\"time\")\nGROUP BY 1 ORDER BY 1"
    }
   ]
  },
  {
   "title": "Demand in $state",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('1 hour', \"time\") AS \"time\", SUM(\"Demand [MW]\") AS \"Demand\"\nFROM cosema.reg_demand\nWHERE state = '$state' AND balanced = '$balanced' AND $__timeFilter(\"time\")\nGROUP BY 1 ORDER BY 1"
    }
   ]
  }
 ]
}