{
 "title": "Emission intensities and regionalized data",
 "time": { "from": "2022-12-31T23:00:00.000Z", "to": "2023-12-31T22:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "state",
    "query": "SHOW TAG VALUES WITH KEY = \"state\" WHERE \"state\" != 'Common' AND \"state\" != 'NW'"
   },
   {
    "name": "mode",
    "query": "SHOW TAG VALUES WITH KEY = \"mode\""
   },
   {
    "name": "balanced",
    "query": "SHOW TAG VALUES WITH KEY = \"balanced\""
   }
  ]
 },
 "panels": [
  {
   "title": "Emissions intensity in $state",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Consumption intensity $tag_state ($tag_mode)",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "mode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2_intensity",
     "select": [
      [
       { "params": [ "Intensity [g/kWh]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "consumption" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
      { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" }
     ]
    },
    {
     "alias": "Generation intensity $tag_state ($tag_mode)",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "mode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2_intensity",
     "select": [
      [
       { "params": [ "Intensity [g/kWh]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
      { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" }
     ]
    },
    {
     "alias": "Consumption intensity DE ($tag_mode)",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "mode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2_intensity",
     "select": [
      [
       { "params": [ "Intensity [g/kWh]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "DE" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "consumption" },
      { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" }
     ]
    },
    {
     "alias": "Generation intensity DE ($tag_mode)",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "mode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2_intensity",
     "select": [
      [
       { "params": [ "Intensity [g/kWh]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "state", "operator": "=", "value": "DE" },
      { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" }
     ]
    }
   ]
  },
  {
   "title": "Emissions intensity forecast",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Forecasted consumption intensity $tag_state",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "mode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2_intensity",
     "select": [
      [
       { "params": [ "Intensity [t/MW]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Consumption" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
      { "condition": "AND", "key": "mode", "operator": "=", "value": "forecast" }
     ]
    },
    {
     "alias": "Forecasted generation intensity $tag_state",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "mode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2_intensity",
     "select": [
      [
       { "params": [ "Intensity [t/MW]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Generation" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
      { "condition": "AND", "key": "mode", "operator": "=", "value": "forecast" }
     ]
    },
    {
     "alias": "Forecasted consumption intensity DE",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "mode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2_intensity",
     "select": [
      [
       { "params": [ "Intensity [t/MW]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Consumption" },
      { "condition": "AND", "key": "mode", "operator": "=", "value": "forecast" }
     ]
    },
    {
     "alias": "Forecasted generation intensity DE",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "mode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2_intensity",
     "select": [
      [
       { "params": [ "Intensity [t/MW]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Generation" },
      { "condition": "AND", "key": "mode", "operator": "=", "value": "forecast" },
      { "condition": "AND", "key": "state", "operator": "!=", "value": "Common" }
     ]
    }
   ]
  },
  {
   "title": "Generation in $state",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "alias": "Hydro $tag_state",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "reg_generation",
     "query": "SELECT sum(\"Generation [MW]\") FROM \"reg_generation\" WHERE ((\"technology\" = 'Hydro Run-of-river and poundage' OR \"technology\" = 'Hydro Water Reservoir')AND \"state\" =~ /^$state$/ AND \"mode\" =~ /^$mode$/ AND \"balanced\" =~ /^$balanced$/) AND $timeFilter GROUP BY time(1h), \"state\" fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Hydro" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
      { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" }
     ]
    },
    {
     "alias": "Biomass $tag_state",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "reg_generation",
     "query": "SELECT sum(\"Generation [MW]\") FROM \"Per_type_gen\" WHERE (\"technology\" = 'Biomass' AND \"country\" =~ /^$state$/) AND $timeFilter GROUP BY time(1h), \"country\" fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Biomass" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
      { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
      { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
     ]
    },
    {
     "alias": "Nuclear $tag_state",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "reg_generation",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Nuclear" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
      { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
      { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
     ]
    },
    {
     "alias": "Lignite $tag_state",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "reg_generation",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Fossil Brown coal/Lignite" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
      { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
      { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
     ]
    },
    {
     "alias": "Hard coal $tag_state",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "reg_generation",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Fossil Hard coal" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
      { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
      { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
     ]
    },
    {
     "alias": "Fossil gas $tag_state",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "reg_generation",
     "query": "SELECT sum(\"Generation [MW]\") FROM \"Per_type_gen\" WHERE ((\"technology\" = 'Fossil Gas' OR \"technology\" = 'Fossil Coal-derived gas') AND \"country\" =~ /^$state$/) AND $timeFilter GROUP BY time(1h), \"country\" fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Fossil Gas" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
      { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
      { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
     ]
    },
    {
     "alias": "Oil $tag_state",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "reg_generation",
     "query": "SELECT sum(\"Generation [MW]\") FROM \"Per_type_gen\" WHERE ((\"technology\" = 'Fossil Gas' OR \"technology\" = 'Fossil Coal-derived gas') AND \"country\" =~ /^$state$/) AND $timeFilter GROUP BY time(1h), \"country\" fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Fossil Oil" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
      { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
      { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
     ]
    },
    {
     "alias": "Other fossil $tag_state",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "reg_generation",
     "query": "SELECT sum(\"Generation [MW]\") FROM \"reg_generation\" WHERE ((\"technology\" = 'Fossil Coal-derived gas' OR \"technology\" = 'Fossil Oil shale' OR \"technology\" = 'Waste' OR \"technology\" = 'Other' OR \"technology\" = 'Fossil Peat') AND \"state\" =~ /^$state$/ AND \"mode\" =~ /^$mode$/ AND \"balanced\" =~ /^$balanced$/) AND $timeFilter GROUP BY time(1h), \"state\" fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Other" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
      { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
      { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
     ]
    },
    {
     "alias": "Wind Onshore $tag_state",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "reg_generation",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Wind Onshore" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
      { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
      { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
     ]
    },
    {
     "alias": "Wind Offshore $tag_state",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "reg_generation",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Wind Offshore" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
      { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
      { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
     ]
    },
    {
     "alias": "Solar $tag_state",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "reg_generation",
     "query": "SELECT sum(\"Total capacity\")  / 4 FROM \"Capacities\" WHERE (\"simulationID\" =~ /^$Scenario$/ AND \"technology\" = 'Renewable' AND \"UnitName\" = 'Solar [MW]') AND $timeFilter GROUP BY time(1h), \"technology\", \"UnitName\" fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Solar" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
      { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
      { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
     ]
    },
    {
     "alias": "Other VRE $tag_state",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "reg_generation",
     "query": "SELECT sum(\"Generation [MW]\") FROM \"reg_generation\" WHERE ((\"technology\" = 'Other renewable' OR \"technology\" = 'Geothermal' OR \"technology\" = 'Marine') AND \"state\" =~ /^$state$/ AND \"mode\" =~ /^$mode$/ AND \"balanced\" =~ /^$balanced$/) AND $timeFilter GROUP BY time(1h), \"state\" fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Other renewable" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
      { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" },
      { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
     ]
    },
    {
     "alias": "Storage charge $tag_state",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "reg_generation",
     "query": "SELECT sum(\"Generation [MW]\") FROM \"Reg_generation\" WHERE (\"technology\" = 'Hydro Pumped Storage' AND \"state\" =~ /^$state$/ AND \"mode\"  =~ /^$mode$/AND \"Generation [MW]\" <= 0 AND \"balanced\" =~ /^$balanced$/) AND $timeFilter GROUP BY time(1h), \"state\" fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Hydro" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
      { "condition": "AND", "key": "mode", "operator": "=~", "value": "/^$mode$/" }
     ]
    },
    {
     "alias": "Storage discharge $tag_state",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "reg_generation",
     "query": "SELECT sum(\"Generation [MW]\") FROM \"Reg_generation\" WHERE (\"technology\" = 'Hydro Pumped Storage' AND \"state\" =~ /^$state$/ AND \"mode\"  =~ /^$mode$/AND \"Generation [MW]\" > 0 AND \"balanced\" =~ /^$balanced$/) AND $timeFilter GROUP BY time(1h), \"state\" fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "Generation [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "technology", "operator": "=", "value": "Hydro" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" },
      { "condition": "AND", "key": "mode", "operator": "=", "value": "api_version" }
     ]
    }
   ]
  },
  {
   "title": "Demand in $state",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "alias": "Demand $tag_state",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "reg_demand",
     "select": [
      [
       { "params": [ "Demand [MW]" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$state$/" },
      { "condition": "AND", "key": "balanced", "operator": "=~", "value": "/^$balanced$/" }
     ]
    }
   ]
  }
 ]
}